// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBtgMrb5vOMujtj5nkvx5iF1wKWuB1b_C8",
    appId: "1:1098469943220:web:5cf7dd10ccf8635f50f4e1",
    messagingSenderId: '1098469943220',
    projectId: 'todo-ad0ca',
    authDomain: 'todo-ad0ca.firebaseapp.com',
    storageBucket: 'todo-ad0ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-QSbqm-SZV9QlTWckthg1om-i8dsQgR0',
    appId: '1:1098469943220:android:5a8c09072315320850f4e1',
    messagingSenderId: '1098469943220',
    projectId: 'todo-ad0ca',
    storageBucket: 'todo-ad0ca.firebasestorage.app',
    
  );
  
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'TODO: Add your iOS API Key here',
    appId: 'TODO: Add your iOS App ID here',
    messagingSenderId: '1098469943220',
    projectId: 'todo-ad0ca',
    storageBucket: 'todo-ad0ca.firebasestorage.app',
    iosBundleId: 'com.company.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'TODO: Add your macOS API Key here',
    appId: 'TODO: Add your macOS App ID here',
    messagingSenderId: '1098469943220',
    projectId: 'todo-ad0ca',
    storageBucket: 'todo-ad0ca.firebasestorage.app',
    iosBundleId: 'com.company.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyBtgMrb5vOMujtj5nkvx5iF1wKWuB1b_C8",
    appId: "1:1098469943220:web:5cf7dd10ccf8635f50f4e1",
    messagingSenderId: '1098469943220',
    projectId: 'todo-ad0ca',
    storageBucket: 'todo-ad0ca.firebasestorage.app',
    authDomain: 'todo-ad0ca.firebaseapp.com',
  );
}
